### ISSUE TITLE
Really 7.6 compatible?

### ISSUE THREAD

**Issue by Schweriner** [bmoex/my_redirects#1]
Thanks for the extension but...
In a TYPO3 7.6 System the Extension throws an error in the backend module due to textField ViewHelper. After fixing that, when creating a new redirect the TCA fieldtype "select" is unknown. I'll try to provide some fixes by time.

**Comment by Schweriner** [comment]
Created a pull request for 7.6 version

**Comment by bmoex** [comment]
Thanks for your input, will test your PR now =)

**Comment by bmoex** [comment]
"Thank you for the upload of your new extension version. It may take up to 15 minutes until it appears in TER."

Uploaded a new version of the extension to the TER; 1.2.0.
I tested the extension in 6.2.17 and 7.6.2, both works as intended. Again, thanks for your input.
