### ISSUE TITLE
Issue with php 7 environment

### ISSUE THREAD

**Issue by kreativpower** [bmoex/my_redirects#6]
#1: PHP Warning: Declaration of Serfhos\MyRedirects\ViewHelper\FlashMessagesViewHelper::render($renderMode = self::RENDER_MODE_UL) should be compatible with TYPO3\CMS\Fluid\ViewHelpers\FlashMessagesViewHelper::render($renderMode = NULL, $as = NULL) in ..\typo3conf\ext\my_redirects\Classes\ViewHelper\FlashMessagesViewHelper.php line 9

Is it possible that you take the following change in your code?

    /**
     * Renders FlashMessages and flushes the FlashMessage queue
     * Note: This disables the current page cache in order to prevent FlashMessage output
     * from being cached.
     *
     * @see \TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController::no_cache
     * @param string $renderMode @deprecated since TYPO3 CMS 7.3. If you need custom output, use <f:flashMessages as="messages"><f:for each="messages" as="message">...</f:for></f:flashMessages>
     * @param string $as The name of the current flashMessage variable for rendering inside
     * @return string rendered Flash Messages, if there are any.
     * @api
     */
    public function render($renderMode = self::RENDER_MODE_UL, $as = null)

**Comment by bmoex** [comment]
Will check! Thanks for the notification!

**Comment by bmoex** [comment]
Remove extending of FlashMessagesViewHelper for 6.2 legacy dependency
